/** Friendly Spark narration generated once and bundled for offline playback. */
export const SPARK_VOICE: Record<string, string> = {
  "A language model first breaks text into tokens.": "/audio/spark/fe89c861401e.wav",
  "Each token gets a starting representation.": "/audio/spark/c49667a8eaed.wav",
  "You are now the token 'bank'.": "/audio/spark/8ff3dcaedfd7.wav",
  "Your starting representation doesn't know the context yet.": "/audio/spark/5ff3671e7b33.wav",
  "Your flashlight is your query: what are you looking for?": "/audio/spark/d11b5e7e8fc2.wav",
  "Each mirror is a key: what that token offers.": "/audio/spark/9de601b86346.wav",
  "A strong match means this token is relevant.": "/audio/spark/90584d6c232b.wav",
  "Now you are 'sat'. Who did the sitting?": "/audio/spark/38e2354e6296.wav",
  "Your attention is shared. It always adds up to 100%.": "/audio/spark/4ebc5c5d1b61.wav",
  "Softmax turns match scores into attention weights.": "/audio/spark/b5b935b3bb42.wav",
  "Now turn around.": "/audio/spark/7c038f748a25.wav",
  "Imagine finishing a sentence without peeking at words not written yet.": "/audio/spark/76f0f11623b1.wav",
  "Those future words stay locked at zero attention. This is the causal mask.": "/audio/spark/287eb21fe0a4.wav",
  "Now we know what matters. Let's take information from it.": "/audio/spark/4926a0db2888.wav",
  "Each token's value carries the information we take from it.": "/audio/spark/9ffc59d96f36.wav",
  "The value changes your representation. You are a river bank.": "/audio/spark/446eb2c35166.wav",
  "Same token. Different context. Different representation.": "/audio/spark/b9accebf57ec.wav",
  "Real Transformers use multiple attention heads.": "/audio/spark/ddbca9b33752.wav",
  "Each head looks for something different.": "/audio/spark/6f80e9c59363.wav",
  "Each head learns different patterns.": "/audio/spark/0253f3dcb964.wav",
  "Now use everything you've gathered.": "/audio/spark/f255dae61995.wav",
  "The model predicts what comes next.": "/audio/spark/15d034eceff3.wav",
  "And the process repeats for the next token.": "/audio/spark/1ff8e87527c9.wav",
  "You just experienced attention.": "/audio/spark/d8123779f260.wav",
  "Look. Weigh. Take information. Predict.": "/audio/spark/67deebc80e0b.wav",
  "Thanks for being a token.": "/audio/spark/b8f74d5c3426.wav",
  "Touch or click the sentence.": "/audio/spark/e1f3ebe37d25.wav",
  "Shine your light on the words.": "/audio/spark/3d2a39e14056.wav",
  "Sweep your light across the words.": "/audio/spark/242e8d3f7463.wav",
  "Look behind you at the locked future words.": "/audio/spark/25f265408305.wav",
  "Aim at 'river' and pinch to absorb it.": "/audio/spark/d95c28459632.wav",
  "Absorb what matters.": "/audio/spark/2c8429d3ef02.wav",
  "Try both lights. Desktop: Tab switches light.": "/audio/spark/0732e5e6a9d8.wav",
  "Hold your light on 'France'.": "/audio/spark/d6211cf37b88.wav",
  "Walk to or point at the word you think comes next, then pinch.": "/audio/spark/0086ab31fe87.wav",
  "Good guess! The model thinks differently. Look at the biggest door.": "/audio/spark/1e547911a2da.wav",
};
